# Generated by Django 5.0.4 on 2024-05-29 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0002_remove_gallery_picture_galleryimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name="galleryimage",
            name="gallery",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gallery_images",
                to="gallery.gallery",
            ),
        ),
        migrations.CreateModel(
            name="RequestGalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="request_gallery_images/")),
                (
                    "gallery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="request_gallery_images",
                        to="gallery.requestgallery",
                    ),
                ),
            ],
        ),
    ]
